language: bash

sudo: required

services:
  - docker

install:
  - docker-compose -f ./docker-compose-travis.yml -p tests up -d 

before_script:
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "sed -i '/auth.pgsql.server/c auth.pgsql.server = pgsql_server:5432' /emqx_auth_pgsql/etc/emqx_auth_pgsql.conf"

script:
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_pgsql compile"
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_pgsql eunit"
  - docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "make -C /emqx_auth_pgsql ct"

after_script:
  - docker-compose -f ./docker-compose-travis.yml -p tests down 
