version: '3'

services:
  erlang:
    image: erlang:22.3
    volumes:
      - ./:/emqx_auth_pgsql
    networks:
      - emqx-bridge
    depends_on:
      - pgsql_server
    tty: true

  pgsql_server:
    image: ${PGSQL_IMAGE}
    restart: always
    environment:
      POSTGRES_PASSWORD: public
      POSTGRES_USER: root
      POSTGRES_DB: mqtt
    networks:
      - emqx-bridge

networks:
  emqx-bridge:
    driver: bridge
